_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-101.pkl"
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, False, True, True] # dcn on res4, res5
OUTPUT_DIR: "output/sparse_inst_r101_dcn_giam"