_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/pvt_v2_b2_li.pth"
  BACKBONE:
    NAME: "build_pyramid_vision_transformer"
  SPARSE_INST:
    ENCODER:
      IN_FEATURES: ["p2", "p3", "p4"]
  PVT:
    NAME: "b2"
    LINEAR: True
    OUT_FEATURES: ["p2", "p3", "p4"]
OUTPUT_DIR: "output/sparse_inst_pvt_b2_linear_giam"