_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/cspdarknet53_ra_256-d05c7c21.pth"
  BACKBONE:
    NAME: "build_cspnet_backbone"
  SPARSE_INST:
    ENCODER:
      IN_FEATURES: ["csp2", "csp3", "csp4"]
  CSPNET:
    NAME: "darknet53"
    OUT_FEATURES: ["csp2", "csp3", "csp4"]
OUTPUT_DIR: "output/sparse_inst_cspdarknet53_giam"